### PR TITLE
Minor python improvements

### PR DESCRIPTION
**Pull request by NuclearPhoenixx**
Made the module import a bit more efficient again and changed two while loops in ```schlitter.py``` in terms of making them shorter.

### CODE REVIEW

**Review by evoyiatzis — APPROVED** [review]

**Comment by NuclearPhoenixx** [comment]
Did you forget to accept the PR? :x

**Comment by evoyiatzis** [comment]
- Changing the way np module is imported in the schlitter.py can cause some problems. for instance the standard python sum will not be available any more - only the numpy.sum version will be used. 
- The efficiency of importing the module is not enhanced (see relevant discussion in stackoverflow https://softwareengineering.stackexchange.com/questions/187403/import-module-vs-from-module-import-function)

**Comment by NuclearPhoenixx** [comment]
* Sorry, big mistake on my part. If you want to, changing the names is an easy fix, like 'sum' for the python sum and 'Sum' for the numpy one. I could still do that (only if you want)
* Sorry again. I don't mean more efficient but somewhat more organised and most importantly you don't have to type np or numpy every time you need it.

**Comment by NuclearPhoenixx** [comment]
Quick follow up question: Are you still active?

**Pull request closed without merging**
